# Generated by Django 4.2 on 2023-05-03 06:59

from django.db import migrations, models
import shorter.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.CharField(default=shorter.tools.create_short_uuid, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('long_url', models.URLField()),
            ],
        ),
    ]
