# Generated by Django 4.2 on 2023-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='custom_name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
